### ISSUE TITLE
throttling date calculation not working

### ISSUE THREAD

**Issue by maxandersen** [aarongustafson/jekyll-webmention_io#122]
I enabled throttling using the example from docs:

```
 throttle_lookups:
    last_week: daily
    last_month: weekly
    last_year: every 2 weeks
    older: monthly
```
 but jekyll webmentions insist that a date from today (2018-12-25 00:00:00 +0100) is always considered "older" meaning it won't check webmentions for new posts.
