### ISSUE TITLE
Tweet that contains what looks to Markdown like an ordered list generates flawed HTML

### ISSUE THREAD

**Issue by dltj** [aarongustafson/jekyll-webmention_io#148]
This is an interesting edge case.  There is a tweet that references my blog post that contains a character sequence that corresponds to Markdown markup for emphasis (e.g. the `*any*` part of the tweet):

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">5. My point being not that major releases are often handled badly, and are disastrous for that reason; but the much more fundamental point that *any* major release is a confession of failure. Failure to keep the promise of compatibility, which the poor user depends on.</p>&mdash; Mike Tⓐylor 🏴󠁧󠁢󠁥󠁮󠁧󠁿 🇬🇧 🇪🇺 (@MikeTaylor) <a href="https://twitter.com/MikeTaylor/status/1408449494241493000?ref_src=twsrc%5Etfw">June 25, 2021</a></blockquote>

What is stored in my `received.yml` file is this:

```yaml
  '1408449494241493000':
    id: '1408449494241493000'
    uri: https://twitter.com/MikeTaylor/status/1408449494241493000
    source: twitter
    pubdate: 2021-06-25 11:38:21.000000000 -04:00
    raw:
      source: https://brid.gy/comment/twitter/DataG/1407879695811723267/1408449494241493000
      verified: true
      verified_date: '2021-06-25T16:41:38+00:00'
      id: 1201321
      private: false
      data:
        author: &16
          name: "Mike Tⓐylor \U0001F3F4\U000E0067\U000E0062\U000E0065\U000E006E\U000E0067\U000E007F
            \U0001F1EC\U0001F1E7 \U0001F1EA\U0001F1FA"
          url: https://twitter.com/MikeTaylor
          photo: https://webmention.io/avatar/pbs.twimg.com/f925d364e8cedcdfc50f4c883ea366fea1f25d22e4660cd7bd66f686c488514c.jpg
        url: https://twitter.com/MikeTaylor/status/1408449494241493000
        name:
        content: |-
          5. My point being not that major releases are often handled badly, and are disastrous for that reason; but the much more fundamental point that *any* major release is a confession of failure. Failure to keep the promise of compatibility, which the poor user depends on.
          <a class="u-mention" href="https://dltj.org/"></a>
          <a class="u-mention" href="https://twitter.com/DataG"></a>
          <a class="u-mention" href="https://twitter.com/bryjbrown"></a>
          <a class="u-mention" href="https://twitter.com/ruthbrarian"></a>
          <a class="u-mention" href="https://www.mypronouns.org/he-him"></a>
        published: '2021-06-25T15:38:21+00:00'
        published_ts: 1624635501
      activity:
        type: reply
        sentence: "Mike Tⓐylor \U0001F3F4\U000E0067\U000E0062\U000E0065\U000E006E\U000E0067\U000E007F
          \U0001F1EC\U0001F1E7 \U0001F1EA\U0001F1FA replied '5. My point being not
          that major releases are often handled badly, and are disas...' to a tweet
          https://dltj.org/article/digital-preservation-software/"
        sentence_html: "<a href=\"https://twitter.com/MikeTaylor\">Mike Tⓐylor \U0001F3F4\U000E0067\U000E0062\U000E0065\U000E006E\U000E0067\U000E007F
          \U0001F1EC\U0001F1E7 \U0001F1EA\U0001F1FA</a> replied '5. My point being
          not that major releases are often handled badly, and are disas...' to a
          tweet <a href=\"https://dltj.org/article/digital-preservation-software/\">https://dltj.org/article/digital-preservation-software/</a>"
      target: https://dltj.org/article/digital-preservation-software/
    author: *16
    type: reply
    content: |-
      <p>
        <li>My point being not that major releases are often handled badly, and are disastrous for that reason; but the much more fundamental point that <em>any</em> major release is a confession of failure. Failure to keep the promise of compatibility, which the poor user depends on.
      <a class="u-mention" href="https://dltj.org/"></p>
      <a class="u-mention" href="https://twitter.com/DataG"></a>
      <a class="u-mention" href="https://twitter.com/bryjbrown"></a>
      <a class="u-mention" href="https://twitter.com/ruthbrarian"></a>
      <a class="u-mention" href="https://www.mypronouns.org/he-him"></a></li>
      </ol>
```

Note the third line of the `content tag` that has a closing `</p>` tag rather than a closing `</a>` tag:

```html
<a class="u-mention" href="https://dltj.org/"></p>
```

This, of course, is really messing with how the browser is rendering the HTML markup.

Two points that I would mark as "unfortunate":
1. I can't point to a live version.  I'm just getting started with Webmentions and `jekyll-webmention_io`, and I haven't deployed it to my live site yet.
2. I don't know Ruby as a programming language, so I don't know where to begin diagnosing the problem.
