### ISSUE TITLE
(optionaly?) generate Jekyll data files with webmentions

### ISSUE THREAD

**Issue by nhoizey** [aarongustafson/jekyll-webmention_io#25]
Using [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/) would allow us to use templates to generate whatever HTML we need, or even other formats, like RSS/Atom.

It would also help fix the issue with avatars size/weight (#24) because we could use the method of our choice for image optimizations. I, for example, would be able to use my [Jelyll Cloudinary plugin](https://nhoizey.github.io/jekyll-cloudinary/).

**Comment by aarongustafson** [comment]
I'm making caching to data files an option.

**Comment by nhoizey** [comment]
Great!

**Comment by aarongustafson** [comment]
Actually, it's probably worth pointing out that the plugin will have default templates but you will be able to supply your own, so there would not be an issue using cloudinary, etc. anyway, even without data files.

**Comment by nhoizey** [comment]
Perfect!

**Comment by aarongustafson** [comment]
New API in _config.yml. I probably won’t get to document until next week:

```
webmentions:
  cache_folder: .cache
  cache_bad_uris_for: 1 # in days
  templates: # one for each tag type
    webmentions: _includes/webmentions.html
  legacy_domains:
    - http://aaron-gustafson.com
    - http://www.aaron-gustafson.com
```

New tag assortment:

```
<h2>Counts</h2>
<p>Total webmentions: {% webmention_count page.url %}</p>

<p>Total likes: {% webmention_count page.url likes %}</p>

<h2>All</h2>
{% webmentions page.url %}

<h2>Replies &amp; Posts</h2>
{% webmentions page.url replies posts %}

<h2>Links</h2>
{% webmention_links page.url %}

<h2>Likes</h2>
{% webmention_likes page.url %}

<h2>Replies</h2>
{% webmention_replies page.url %}

<h2>Reposts</h2>
{% webmention_reposts page.url %}
```
