### ISSUE TITLE
How to show a webmention without any content?

### ISSUE THREAD

**Issue by nhoizey** [aarongustafson/jekyll-webmention_io#54]
I received a webmention that doesn't show anything with the default template:
https://nicolas-hoizey.com/2017/07/so-long-disqus-hello-webmentions.html#webmention-447800

Here's the data:

```yaml
  '447800':
    id: '447800'
    url: https://open-time.net/post/2017/07/29/Webmentions-en-coreen
    source: false
    pubdate: 2017-07-29 07:22:51.000000000 +02:00
    raw:
      source: https://open-time.net/post/2017/07/29/Webmentions-en-coreen
      verified: true
      verified_date: '2017-07-29T05:22:51+00:00'
      id: 447800
      private: false
      data:
        url: https://open-time.net/post/2017/07/29/Webmentions-en-coreen
        name: 
        content: 
        published: 
        published_ts: 
      activity:
        type: link
        sentence: https://open-time.net/post/2017/07/29/Webmentions-en-coreen posted
          '' linking to https://nicolas-hoizey.com/2017/07/so-long-disqus-hello-webmentions.html
        sentence_html: <a href="https://open-time.net/post/2017/07/29/Webmentions-en-coreen">someone</a>
          posted '' linking to <a href="https://nicolas-hoizey.com/2017/07/so-long-disqus-hello-webmentions.html">https://nicolas-hoizey.com/2017/07/so-long-disqus-hello-webmentions.html</a>
      target: https://nicolas-hoizey.com/2017/07/so-long-disqus-hello-webmentions.html
    type: link
    content: ''
```

Maybe it could use the URL if there's no content.
