### ISSUE TITLE
Performance impact on build

### ISSUE THREAD

**Issue by nhoizey** [aarongustafson/jekyll-webmention_io#81]
Hi, my build time is now really long (around 2500 seconds, which means 40 minutes), and I thinks most of this time comes from Webmentions.

I have more than 500 posts.

My `received.yml` file has morethan 16000 lines.

Here is my Webmentions configuration:

```
webmentions:
  username: nicolas-hoizey.com
  cache_folder: _data/webmentions
  cache_bad_uris_for: 5
  pause_lookups: false
  collections:
    - notes
  templates:
    count: _includes/webmentions/count.html
    likes: _includes/webmentions/likes.html
    reposts: _includes/webmentions/reposts.html
    webmentions: _includes/webmentions/webmentions.html
  js: false
  legacy_domains:
    - http://nicolas-hoizey.com
  throttle_lookups:
    last_week: daily
    last_month: daily
    last_year: weekly
    older: every 2 weeks
```

I made a flamegraph (SVG file in the zip) with [rbspy](https://github.com/rbspy/rbspy):
[rbspy-2018-04-27-8OI5yinIKQ.flamegraph.zip](https://github.com/aarongustafson/jekyll-webmention_io/files/1957471/rbspy-2018-04-27-8OI5yinIKQ.flamegraph.zip)

The command I ran is:

```shell
JEKYLL_ENV=production sudo --preserve-env rbspy record --rate 10 -- bundle exec jekyll build --config _config.yml,_config_credentials.yml
```

This is the first time I use a flamegraph, so I might be jumping to conclusions, but it looks like Webmentions gathering is taking most of the build time:
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/78213/39394232-d7a58030-4acf-11e8-8114-4fd67eac6a49.png">

I have a few questions/suggestions:
- Does it look for Webmentions in webmention.io twice if I have an entry in `legacy_domains`?
  - If the legacy domain is the same as current one but HTTP instead of HTTPS, would it be possible to query webmention.io without the protocol?
  - Or would it be possible to configure a throttle for legacy domains?
- Would it be faster with one cache file per post, instead of one single huge cache file?
- Would it be possible to run Webmentions gathering asynchronously, with a new `webmentions_gather` command, instead of during each build?
