### ISSUE TITLE
Throttling doesn't apply to posts without webmentions

### ISSUE THREAD

**Issue by jordanmerrick** [aarongustafson/jekyll-webmention_io#84]
I've recently added webmentions to my Jekyll blog, which has ~800 posts going back a number of years. Only about four recent posts have received webmentions. My site's build time is currently around five minutes, but throttling seems to make no difference. I'm using the following throttling configuration:

```
  throttle_lookups:
    last_week: daily
    last_month: weekly
    last_year: every 2 weeks
    older: monthly
```

What I seem to be experiencing is that only posts which have received webmentions are throttled. So for all other posts that have no webmentions, they're checked every time. Is that right? If so, can there be a way to specify that throttling should apply to all posts, not just ones that have received webmentions previously? In my case, this could possibly decrease build times significantly.
